### ISSUE TITLE
Pylance doesn't like the import from the root module

### ISSUE THREAD

**Issue by hannesbruger** [team23/pydantic-apply#17]
Python: 3.12
Editor: VSCode 1.88.0 (latest as of 2024-04-17)
pydantic-apply: 0.5.7
OS: macOS 14.4.1

Usually I would import the `ApplyModelMixin` with `from pydantic_apply import ApplyModelMixin`.
However, Pylance doesn't like that and shows an error:
```
"ApplyModelMixin" is not exported from module "pydantic_apply"
  Import from "pydantic_apply.apply" instead
```
with a link tp [reportPrivateImportUsage](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportPrivateImportUsage)

A similar issue was reported [for pytorch](https://github.com/microsoft/pylance-release/issues/2953) with an explanation of this behavior in [this comment](https://github.com/microsoft/pylance-release/issues/2953#issuecomment-1168408943).

And in fact, if I add `from .apply import ApplyModelMixin as ApplyModelMixin` to the `__init__` of the module it works.

From [PEP 484 about stub files](https://peps.python.org/pep-0484/#stub-files):

> Modules and variables imported into the stub are not considered exported from the stub unless the import uses the import ... as ... form or the equivalent from ... import ... as ... form. (UPDATE: To clarify, the intention here is that only names imported using the form X as X will be exported, i.e. the name before and after as must be the same.)

Would it make sense to add this line?
I can open a pull request, if that helps.

**Comment by hannesbruger** [comment]
I opened an according PR: https://github.com/team23/pydantic-apply/pull/18

**Comment by ddanier** [comment]
Merged your PR just now. Will create a new patch level release containing this change.
